image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

auth:
  rootPassword: "RootPass123!"
  user: "appuser"
  password: "Kaizen123!"
  database: "appdb"

storage:
  size: 5Gi
  className: ""  # можно оставить пустым или указать существующий StorageClass

service:
  port: 3306
