apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  NODE_ENV: "production"
  # Добавь любые не-секретные настройки API тут
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  NODE_ENV: "production"
  # Фронт должен брать адрес API из переменной окружения
  API_BASE_URL: "http://api-service.default.svc.cluster.local:3001"