apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
stringData:
  DB_HOST: "mysql.default.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "kaizen"
  DB_PASSWORD: "Hello123!"
  DB_NAME: "appdb"
  JWT_SECRET: "please_change_me"
---
apiVersion: v1
kind: Secret
metadata:
  name: web-secret
type: Opaque
stringData:
  # Если фронт сам добавляет /api в путях, оставь BASE без /api
  API_BASE_URL: "http://api-service.default.svc.cluster.local:3001"
